import { useCallback, useEffect, useMemo, useState } from 'react'
import { Banknote, CreditCard, Minus, PackageSearch, Plus, Search, ShoppingCart, Trash2, X, Zap } from 'lucide-react'
import API_URL, { apiFetch, enviarVenda } from '../config/api'
import { imagemProdutoUrl } from '../utils/cloudinary'
import ComprovantePdvModal from '../components/ComprovantePdvModal'

const moeda = valor => Number(valor || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const formas = [
  ['PIX','PIX',Zap], ['DINHEIRO','Dinheiro',Banknote],
  ['CARTAO_DEBITO','Débito',CreditCard], ['CARTAO_CREDITO','Crédito',CreditCard], ['OUTRO','Outro',CreditCard]
]

export default function Pdv({ token, loja }) {
  const [produtos,setProdutos]=useState([]), [clientes,setClientes]=useState([])
  const [carrinho,setCarrinho]=useState([]), [busca,setBusca]=useState(''), [erro,setErro]=useState('')
  const [carregando,setCarregando]=useState(true), [enviando,setEnviando]=useState(false), [carrinhoAberto,setCarrinhoAberto]=useState(false)
  const [clienteId,setClienteId]=useState(''), [forma,setForma]=useState(loja?.financeiroAtivo?'PIX':'NAO_INFORMADO')
  const [desconto,setDesconto]=useState(''), [recebido,setRecebido]=useState(''), [comprovante,setComprovante]=useState(null)

  const carregar=useCallback(async()=>{setErro('');setCarregando(true);try{const [rp,rc]=await Promise.all([apiFetch(`${API_URL}/produtos`,{headers:{Authorization:`Bearer ${token}`}}),apiFetch(`${API_URL}/clientes`,{headers:{Authorization:`Bearer ${token}`}})]);setProdutos(await rp.json());setClientes(await rc.json())}catch(e){setErro(e.message)}finally{setCarregando(false)}},[token])
  useEffect(()=>{carregar()},[carregar])
  const filtrados=useMemo(()=>produtos.filter(p=>`${p.nome} ${p.categoria?.nome||''}`.toLowerCase().includes(busca.toLowerCase())),[produtos,busca])
  const quantidadeTotal=carrinho.reduce((s,i)=>s+i.quantidade,0)
  const subtotal=carrinho.reduce((s,i)=>s+Number(i.produto.preco||0)*i.quantidade,0)
  const descontoNumero=Math.max(0,Number(desconto||0)), total=Math.max(0,subtotal-descontoNumero)
  const troco=forma==='DINHEIRO'?Math.max(0,Number(recebido||0)-total):0

  function adicionar(produto){if(produto.quantidadeEstoque<=0)return;setCarrinho(atual=>{const item=atual.find(i=>i.produto.id===produto.id);if(item){if(item.quantidade>=produto.quantidadeEstoque)return atual;return atual.map(i=>i.produto.id===produto.id?{...i,quantidade:i.quantidade+1}:i)}return[...atual,{produto,quantidade:1}]})}
  function alterar(id,delta){setCarrinho(atual=>atual.map(i=>i.produto.id===id?{...i,quantidade:Math.min(i.produto.quantidadeEstoque,i.quantidade+delta)}:i).filter(i=>i.quantidade>0))}

  async function finalizar(){setErro('');if(!carrinho.length){setErro('Adicione pelo menos um produto.');return}if(loja?.financeiroAtivo&&descontoNumero>=subtotal){setErro('O desconto precisa ser menor que o subtotal.');return}if(loja?.financeiroAtivo&&forma==='DINHEIRO'&&Number(recebido||0)<total){setErro('O valor recebido é menor que o total.');return}setEnviando(true);try{const resposta=await enviarVenda(`${API_URL}/vendas`,{clienteId:clienteId?Number(clienteId):null,formaPagamento:loja?.financeiroAtivo?forma:'NAO_INFORMADO',desconto:loja?.financeiroAtivo?descontoNumero:0,valorRecebido:loja?.financeiroAtivo&&forma==='DINHEIRO'?Number(recebido):null,itens:carrinho.map(i=>({produtoId:i.produto.id,quantidade:i.quantidade}))},token);const venda=await resposta.json();setComprovante(venda);setCarrinho([]);setClienteId('');setDesconto('');setRecebido('');setCarrinhoAberto(false);await carregar()}catch(e){setErro(e.message)}finally{setEnviando(false)}}

  const painel=<div className="pdv-cart glass-panel !bg-[var(--bg-color)] p-5 space-y-5">
    <div className="flex justify-between items-center"><div><h2 className="text-2xl font-black">Venda atual</h2><p className="opacity-55">{quantidadeTotal} {quantidadeTotal===1?'item':'itens'}</p></div><button onClick={()=>setCarrinhoAberto(false)} className="touch-button lg:hidden"><X/></button></div>
    {!carrinho.length?<div className="empty-state !min-h-40"><ShoppingCart size={40}/><strong>Carrinho vazio</strong><span>Toque nos produtos para adicionar.</span></div>:<div className="space-y-2 max-h-[34dvh] overflow-y-auto">{carrinho.map(item=><div key={item.produto.id} className="pdv-cart-item"><div className="min-w-0"><strong className="block truncate">{item.produto.nome}</strong>{loja?.financeiroAtivo&&<span className="opacity-55 text-sm">{moeda(item.produto.preco)} cada</span>}</div><div className="flex items-center gap-1"><button onClick={()=>alterar(item.produto.id,-1)} className="touch-button !min-w-10 !min-h-10"><Minus size={18}/></button><strong className="w-8 text-center">{item.quantidade}</strong><button onClick={()=>alterar(item.produto.id,1)} className="touch-button !min-w-10 !min-h-10"><Plus size={18}/></button><button onClick={()=>setCarrinho(c=>c.filter(i=>i.produto.id!==item.produto.id))} className="touch-button !min-w-10 !min-h-10 text-rose-500"><Trash2 size={18}/></button></div></div>)}</div>}
    <label className="field-label">Cliente (opcional)<select className="control-field" value={clienteId} onChange={e=>setClienteId(e.target.value)}><option value="">Consumidor não identificado</option>{clientes.map(c=><option value={c.id} key={c.id}>{c.nome}</option>)}</select></label>
    {loja?.financeiroAtivo&&<><div><p className="field-label mb-2">Como foi pago?</p><div className="grid grid-cols-2 gap-2">{formas.map(([id,nome,Icon])=><button key={id} onClick={()=>setForma(id)} className={`pdv-payment ${forma===id?'selected':''}`}><Icon size={20}/>{nome}</button>)}</div></div><div className="grid grid-cols-2 gap-3"><label className="field-label">Desconto<input className="control-field" inputMode="decimal" type="number" min="0" step="0.01" value={desconto} onChange={e=>setDesconto(e.target.value)} placeholder="R$ 0,00"/></label>{forma==='DINHEIRO'&&<label className="field-label">Recebido<input className="control-field" inputMode="decimal" type="number" min="0" step="0.01" value={recebido} onChange={e=>setRecebido(e.target.value)} placeholder={moeda(total)}/></label>}</div><div className="border-t border-current/15 pt-4 space-y-2"><div className="flex justify-between opacity-60"><span>Subtotal</span><span>{moeda(subtotal)}</span></div>{descontoNumero>0&&<div className="flex justify-between text-emerald-600"><span>Desconto</span><span>- {moeda(descontoNumero)}</span></div>}<div className="flex justify-between text-2xl font-black"><span>Total</span><span>{moeda(total)}</span></div>{forma==='DINHEIRO'&&<div className="flex justify-between font-bold"><span>Troco</span><span>{moeda(troco)}</span></div>}</div></>}
    {erro&&<div role="alert" className="error-box">{erro}</div>}<button disabled={enviando||!carrinho.length} onClick={finalizar} className="btn-primary mobile-action w-full flex items-center justify-center gap-2"><ShoppingCart size={21}/>{enviando?'Registrando com segurança...':loja?.financeiroAtivo?'Concluir venda':'Confirmar saída'}</button>
  </div>

  return <div className="page-shell max-w-[1500px] mx-auto pb-36 lg:pb-8"><header className="page-header"><div><h1>Vendas</h1><p>{loja?.financeiroAtivo?'Venda completa, recebimento e comprovante':'Saída de vários produtos em uma operação'}</p></div></header>
    {erro&&!carrinhoAberto&&<div className="error-box mb-4">{erro}</div>}<div className="pdv-layout"><section className="space-y-4"><div className="glass-panel mobile-panel relative"><Search className="absolute left-7 top-1/2 -translate-y-1/2 opacity-45"/><input autoFocus className="control-field w-full !pl-12" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar produto..."/></div>{carregando?<div className="glass-panel empty-state"><PackageSearch className="animate-pulse"/><strong>Carregando produtos...</strong></div>:<div className="pdv-grid">{filtrados.map(produto=>{const noCarrinho=carrinho.find(i=>i.produto.id===produto.id)?.quantidade||0;return <button disabled={!produto.quantidadeEstoque} onClick={()=>adicionar(produto)} key={produto.id} className="pdv-product glass-panel"><div className="pdv-product-image">{produto.imagemUrl?<img src={imagemProdutoUrl(produto.imagemUrl,500)} alt=""/>:<PackageSearch/>}{noCarrinho>0&&<b>{noCarrinho}</b>}</div><div><span className="opacity-50 text-xs font-bold uppercase">{produto.categoria?.nome||'Produto'}</span><h2>{produto.nome}</h2>{loja?.financeiroAtivo&&<strong className="text-lg">{moeda(produto.preco)}</strong>}<p>{produto.quantidadeEstoque} em estoque</p></div></button>})}</div>}</section><aside className="hidden lg:block">{painel}</aside></div>
    <button onClick={()=>setCarrinhoAberto(true)} className="pdv-mobile-bar lg:hidden"><span><ShoppingCart size={22}/><b>{quantidadeTotal} itens</b></span>{loja?.financeiroAtivo&&<strong>{moeda(total)}</strong>}</button>{carrinhoAberto&&<div className="fixed inset-0 z-[75] bg-black/80 flex items-end lg:hidden" onClick={()=>setCarrinhoAberto(false)}><div className="w-full max-h-[94dvh] overflow-y-auto rounded-t-2xl" onClick={e=>e.stopPropagation()}>{painel}</div></div>}<ComprovantePdvModal venda={comprovante} onClose={()=>setComprovante(null)}/>
  </div>
}
