import { useCallback, useEffect, useState } from 'react'
import { ArrowDownToLine, ArrowUpFromLine, History } from 'lucide-react'
import API_URL, { apiFetch } from '../config/api'

const moeda = valor => Number(valor || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})

export default function CaixaAdministracao({ token, ativo }) {
  const [sessoes,setSessoes]=useState([]),[tipo,setTipo]=useState('SUPRIMENTO'),[valor,setValor]=useState(''),[descricao,setDescricao]=useState(''),[erro,setErro]=useState('')
  const carregar=useCallback(async()=>{if(!ativo)return;try{const r=await apiFetch(`${API_URL}/caixas?tamanho=10`,{headers:{Authorization:`Bearer ${token}`}});setSessoes((await r.json()).content||[])}catch(e){setErro(e.message)}},[ativo,token])
  useEffect(()=>{carregar()},[carregar])
  if(!ativo)return null
  async function movimentar(event){event.preventDefault();setErro('');try{await apiFetch(`${API_URL}/caixas/movimentos`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({tipo,valor:Number(valor),descricao})});setValor('');setDescricao('');await carregar()}catch(e){setErro(e.message)}}
  return <section className="glass-panel p-6 space-y-5"><div className="flex gap-3 items-center"><History/><div><h2 className="font-black text-lg">Caixas por operadora</h2><p className="opacity-55">Abertura, fechamento, sangria e conferência.</p></div></div><form onSubmit={movimentar} className="grid sm:grid-cols-[1fr_1fr_2fr_auto] gap-3 items-end"><label className="field-label">Movimento<select value={tipo} onChange={e=>setTipo(e.target.value)} className="control-field w-full mt-2"><option value="SUPRIMENTO">Suprimento</option><option value="SANGRIA">Sangria</option></select></label><label className="field-label">Valor<input required min="0.01" step="0.01" type="number" value={valor} onChange={e=>setValor(e.target.value)} className="control-field w-full mt-2"/></label><label className="field-label">Motivo<input required maxLength="300" value={descricao} onChange={e=>setDescricao(e.target.value)} className="control-field w-full mt-2"/></label><button className="btn-primary mobile-action flex gap-2 justify-center">{tipo==='SUPRIMENTO'?<ArrowDownToLine size={18}/>:<ArrowUpFromLine size={18}/>} Registrar</button></form>{erro&&<p className="error-box">{erro}</p>}<div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="text-xs opacity-55"><th className="p-2">Operadora</th><th className="p-2">Abertura</th><th className="p-2">Status</th><th className="p-2">Esperado</th><th className="p-2">Informado</th><th className="p-2">Diferença</th></tr></thead><tbody>{sessoes.map(c=><tr className="border-t border-current/10" key={c.id}><td className="p-2">{c.operador}</td><td className="p-2">{new Date(c.abertaEm).toLocaleString('pt-BR')}</td><td className="p-2">{c.status}</td><td className="p-2">{moeda(c.status==='ABERTO'?c.saldoAtual:c.saldoEsperado)}</td><td className="p-2">{c.saldoInformado==null?'—':moeda(c.saldoInformado)}</td><td className={`p-2 font-bold ${Number(c.diferenca)<0?'text-rose-500':Number(c.diferenca)>0?'text-amber-500':''}`}>{c.diferenca==null?'—':moeda(c.diferenca)}</td></tr>)}</tbody></table></div></section>
}
